# Generated by Django 5.2.5 on 2025-08-14 20:14

import EasyCert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyCert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivousuario',
            options={'verbose_name': 'Archivo de Usuario', 'verbose_name_plural': 'Archivos de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='archivousuario',
            name='archivo',
            field=models.FileField(upload_to=EasyCert.models.archivo_usuario_upload_path),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to=EasyCert.models.contrato_upload_path),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_constancia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=20),
        ),
    ]
